<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-4" name="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest" tests="49" failures="12" timestamp="23 Jul 2021 15:20:09 GMT" time="1796.399" errors="0">
  <testcase name="checkSavedVoucher4AndTryingToUpdateVoucherRateGreaterThanCreditLimit" time="9.269" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPostingDetailsWithRateLessThanStandardRate" time="10.194" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkUpdatedLayoutAndDeleteTheLayout" time="19.401" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingSalesInvoiceVATVoucher4WithRateAsLessThanCreditLimit" time="23.107" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingSalesInvoiceVATVoucher4WithRateAsLessThanCreditLimit(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingSalesInvoiceVATVoucher4WithRateAsLessThanCreditLimit -->
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher3" time="13.302" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkInvoiceDesignOptions" time="7.714" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkEmailOptionInSalesInvoiceVAT" time="85.046" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPrintPdfOfSalesInvoiceVAT" time="37.935" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavedVoucher2InSalesINvoiceVATWithFormulaControl" time="6.402" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkEraseAllTransactionsAfterCompletingAllValidations" time="8.982" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher2" time="13.335" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher5WithStockItem" time="23.348" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingPurchaseVoucherVATVoucher5WithStockItem(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATVoucher5WithStockItem -->
  <testcase name="checkFieldsTabOptions" time="0.889" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher3WithRateFormulaWithAbbrevation" time="35.991" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingPurchaseVoucherVATVoucher3WithRateFormulaWithAbbrevation(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATVoucher3WithRateFormulaWithAbbrevation -->
  <testcase name="checkCreatingDocumentSet" time="62.259" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavedVoucher3InSalesINvoiceVATWithFormulaControl" time="2.452" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkUpdatingBuyerPricebookFormulaForPurchaseVoucherVAT" time="11.276" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPostingDetailsWithGreaterThanAndUpdatingRateToLessThanStandardRate" time="16.952" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkPostingDetailsWithGreaterThanAndUpdatingRateToLessThanStandardRate(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPostingDetailsWithGreaterThanAndUpdatingRateToLessThanStandardRate -->
  <testcase name="checkEditingAndUpdatingDocumentSetForDelete" time="36.831" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkDragandDropHeaderFiledsAndBodyFiledsIntoLayout" time="190.336" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkChangingRatePreloadBehaviourToRateSalesInvoiceVAT" time="13.372" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkCreatingDocumentSetForDelete" time="21.281" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher1" time="13.563" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkUpdatingBuyerPricebookFormulaForSalesInvoiceVATVoucher3" time="13.110" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPrintPdfOfSalesInvoiceVATWithImportedXML" time="57.116" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavedVoucherInSalesINvoiceVAT" time="6.537" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkUpdatingBuyerPricebookFormulaWithAbbrivationForPurchaseVoucherVAT" time="13.120" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkEmailOptionInPurchaseVoucherVAT" time="89.810" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPrintPdfOfPurchaseVoucherVATWithImportedXML" time="56.985" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPrintPdfOfPurchaseVoucherVATWithDocumentSetVendorA" time="50.243" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingSalesInvoiceVATVoucher2WithRateFormula" time="42.077" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingSalesInvoiceVATVoucher2WithRateFormula(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:318)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingSalesInvoiceVATVoucher2WithRateFormula -->
  <testcase name="checkPrintScreenOptions" time="3.201" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingSalesInvoiceVATVoucher3WithRateFormula" time="42.090" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingSalesInvoiceVATVoucher3WithRateFormula(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingSalesInvoiceVATVoucher3WithRateFormula -->
  <testcase name="checkPrintPdfOfPurchaseVoucherVATWithDocumentSetVendorB" time="36.987" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkLayoutOptions" time="2.547" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPrintPdfOfPurchaseVoucherVAT" time="36.685" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher1WithoutRateFormula" time="53.996" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingPurchaseVoucherVATVoucher1WithoutRateFormula(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATVoucher1WithoutRateFormula -->
  <testcase name="checksalesInvoiceVatWithBuyerSellerPriceBooklist" time="58.468" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checksalesInvoiceVatWithBuyerSellerPriceBooklist(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checksalesInvoiceVatWithBuyerSellerPriceBooklist -->
  <testcase name="checkDeletingDocumentSetForDelete" time="17.411" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher2WithRateFormula" time="35.910" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingPurchaseVoucherVATVoucher2WithRateFormula(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATVoucher2WithRateFormula -->
  <testcase name="checkEditingLayoutByAddingFields" time="54.917" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkUpdatingBuyerPricebookFormulaForSalesInvoiceVAT" time="11.242" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingPurchasesVatDesignLayout" time="209.933" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPurchaseVoucherVATWithBinItemAutoAllocateInBinPopup" time="31.059" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkPurchaseVoucherVATWithBinItemAutoAllocateInBinPopup(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPurchaseVoucherVATWithBinItemAutoAllocateInBinPopup -->
  <testcase name="checkChangeFieldPropertiesInLyout" time="105.673" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher4WithStockItem" time="24.748" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkSavingPurchaseVoucherVATVoucher4WithStockItem(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATVoucher4WithStockItem -->
  <testcase name="checkChangingRatePreloadBehaviourToRatePurchaseVoucherVAT" time="11.473" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPrintPdfOfPurchaseVoucherVATWithCreatedLayout" time="48.008" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest"/>
  <testcase name="checkPostingDetailsWithEqualsToAndUpdatingRateToGreaterThanStandardRate" time="19.816" classname="com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.checkPostingDetailsWithEqualsToAndUpdatingRateToGreaterThanStandardRate(BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPostingDetailsWithEqualsToAndUpdatingRateToGreaterThanStandardRate -->
</testsuite> <!-- com.focus.testcases.BuyerSellerPricebookAndVoucherPrintPDFEmailValidationsTest -->
