<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-4" name="com.focus.testcases.PurchaseVouchersVATTest" tests="21" failures="2" timestamp="23 Jul 2021 15:20:09 GMT" time="436.020" errors="0">
  <testcase name="checkSavingPurchaseVoucherVATVoucher2WithBatchItem" time="18.423" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher1WithPurchaseOrderLink" time="34.235" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher3SavingVoucher4" time="27.220" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher3WithStockItem" time="19.298" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkEditingPurchaseVoucherVATVoucher3AddRow2AndUpdate" time="18.514" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher2SavingVoucher3" time="28.265" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher4WithBinItem" time="21.334" classname="com.focus.testcases.PurchaseVouchersVATTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVouchersVATTest.checkSavingPurchaseVoucherVATVoucher4WithBinItem(PurchaseVouchersVATTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATVoucher4WithBinItem -->
  <testcase name="checkVerifingDetailsOfSavedPurchaseVoucherVATInHomepage" time="5.586" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifingTriggersOptionInPurchaseVAT" time="9.210" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkEditingPurchaseVoucherVATVoucher2AddRow2AndUpdate" time="19.621" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher5SavingVoucher6" time="35.842" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingAndDeletingPurchaseVoucherVATVoucher5" time="13.648" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingAndDeletingPurchaseVoucherVATVoucher6" time="12.955" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher4With2RowsAndBinItem" time="20.880" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkRulesInPurchaseVoucherVat" time="20.913" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingAndDeletingPurchaseVoucherVATVoucher3" time="11.655" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkEditingPurchaseVoucherVATVoucher4AddRow3AndUpdate" time="22.735" classname="com.focus.testcases.PurchaseVouchersVATTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.PurchaseVouchersVATTest.checkEditingPurchaseVoucherVATVoucher4AddRow3AndUpdate(PurchaseVouchersVATTest.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkEditingPurchaseVoucherVATVoucher4AddRow3AndUpdate -->
  <testcase name="checkEditingPurchaseVoucherVATVoucher5AddRow2AndUpdate" time="24.142" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkSavingPurchaseVoucherVATVoucher5WithRMAItem" time="23.724" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingAndDeletingPurchaseVoucherVATVoucher4" time="11.295" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
  <testcase name="checkVerifyingPurchaseVoucherVATVoucher4SavingVoucher5" time="36.525" classname="com.focus.testcases.PurchaseVouchersVATTest"/>
</testsuite> <!-- com.focus.testcases.PurchaseVouchersVATTest -->
